### ISSUE TITLE
How to get the data.npz?

### ISSUE THREAD

**Issue by Andyyoung0507** [biggsbenjamin/earlyexitnet#1]
Hi, I am interested in your work. When i try to reproduce this work. I use the download_data.sh to get the data.npz. But the data was not downloaded in the target dir. I use the web url to download it directly, unfortunately i don't have the access to the document in google drive. So How can i  get the data.npz? Thank you!

**Comment by biggsbenjamin** [comment]
Hi Andy, thanks for your message. Just as a heads up, I'm not really maintaining this repo at the moment so use it at your own risk. This repo is primarily a reimplementation of the original repo using pytorch.
With respect to your question, I use the built in pytorch data loaders to get the data for my repo rather than the script from the original branchynet repo so I'm not sure how theirs work. 
Sorry I can't be more help!

**Comment by Andyyoung0507** [comment]
OK, thanks.
